name: Braket Unit Tests - Verbose
on: [push, pull_request, workflow_dispatch]
jobs:
  braket-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          pip install amazon-braket-sdk numpy
      - run: python Braket/build_circuit.py
      - run: python Braket/run_circuit.py
      - run: python Braket/analyze_results.py