name: AWS Braket Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        set -x
        pip install amazon-braket-sdk

    - name: List Assets
      run: |
        set -x
        ls -R

    - name: Run Braket Tests
      run: |
        set -x
        python Braket/double_hadamard_test.py | tee braket_results.log

    - name: Show Results
      run: |
        set -x
        cat braket_results.log
