name: Cirq Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        set -x
        pip install cirq numpy

    - name: List Assets
      run: |
        set -x
        ls -1
        ls Cirq

    - name: Run Cirq Tests
      run: |
        set -x
        python Cirq/hadamard_test.py | tee cirq_results.log
        status=${PIPESTATUS[0]}
        echo "exit code: $status" | tee -a cirq_results.log
        exit $status

    - name: Show Results
      run: |
        set -x
        cat cirq_results.log
