name: Code Quality Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint-and-security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install tools
      run: |
        pip install flake8 bandit black

    - name: Run Lint (flake8)
      run: |
        flake8 .

    - name: Run Security Checks (bandit)
      run: |
        bandit -r .

    - name: Check Formatting (black)
      run: |
        black --check .