name: PennyLane Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        set -x
        pip install pennylane numpy

    - name: List Assets
      run: |
        set -x
        ls -R

    - name: Run PennyLane Tests
      run: |
        set -x
        python PennyLane/hadamard_test.py | tee pennylane_results.log
        status=${PIPESTATUS[0]}
        echo "exit code: $status" | tee -a pennylane_results.log
        exit $status

    - name: Show Results
      run: |
        set -x
        cat pennylane_results.log
