name: Qiskit Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        set -x
        pip install qiskit qiskit-aer numpy

    - name: List Assets
      run: |
        set -x
        ls -R

    - name: Run Qiskit Tests
      run: |
        set -x
        python Qiskit/hadamard_test.py | tee qiskit_results.log

    - name: Show Results
      run: |
        set -x
        cat qiskit_results.log
