name: Qiskit Unit Tests - Verbose
on: [push, pull_request, workflow_dispatch]
jobs:
  qiskit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          pip install qiskit qiskit-aer numpy
      - run: python Qiskit/build_circuit.py
      - run: python Qiskit/run_circuit.py
      - run: python Qiskit/analyze_results.py