name: Quantum Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        framework: [Qiskit, Cirq, PennyLane, Braket]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install numpy
        if [[ "${{ matrix.framework }}" == "Qiskit" ]]; then pip install qiskit qiskit-aer; fi
        if [[ "${{ matrix.framework }}" == "Cirq" ]]; then pip install cirq; fi
        if [[ "${{ matrix.framework }}" == "PennyLane" ]]; then pip install pennylane; fi
        if [[ "${{ matrix.framework }}" == "Braket" ]]; then pip install amazon-braket-sdk; fi

    - name: Run Tests
      run: |
        echo "🔍 Running tests for ${{ matrix.framework }}"
        python ${{ matrix.framework }}/hadamard_test.py